# Practice

In [2]:
import torch, numpy as np

In [3]:
torch.__version__

'2.1.0+cu118'

In [4]:
arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [5]:
x = torch.from_numpy(arr)
x

tensor([0, 1, 2, 3, 4])

In [6]:
xx = torch.as_tensor(arr)
xx

tensor([0, 1, 2, 3, 4])

torch.from_numpy() and torch.as_tensor() creates direct link to np array and if u change the np array, tensor changes too.

But torch.tensor() doesn't have direct link

In [7]:
my_tensor = torch.tensor(arr)


In [11]:
arr[0]=9999
print(arr)
print(x)
print(xx)
print(my_tensor)

[9999    1    2    3    4]
tensor([9999,    1,    2,    3,    4])
tensor([9999,    1,    2,    3,    4])
tensor([0, 1, 2, 3, 4])


torch.Tensor() creats Float tensor

In [14]:
ftensor = torch.Tensor(arr)
print(arr.dtype)
ftensor.dtype

int64


torch.float32

In [17]:
torch.tensor([1,2,3,4],dtype=torch.float32)

tensor([1., 2., 3., 4.])

In [20]:
torch.tensor([1,2,3,4]).type(dtype=torch.float32)


tensor([1., 2., 3., 4.])

In [22]:
t = torch.zeros(5,5)
t

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [23]:
torch.randn_like(t)

tensor([[ 0.0170, -0.2891, -1.8887, -1.5041,  1.1930],
        [ 0.6828,  1.0482, -0.8445,  0.7498, -0.3203],
        [-0.5353,  0.8234,  0.2207, -0.7559, -1.7559],
        [ 0.7564,  0.6326,  2.1727, -1.4556, -0.5989],
        [-0.1442, -1.6590, -0.8087, -0.0099,  0.9380]])

In [24]:
torch.rand_like(t).shape == t.shape

True

In [25]:
torch.manual_seed(42)

In [27]:
a = torch.arange(10)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [29]:
a.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

.shape() and .view() are almost the same.

In [30]:
# Infer what the 2nd dimention would be

a.reshape(5,-1)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [31]:
a = torch.tensor([1,2,3])
b = torch.tensor([7,5,3])

In [32]:
a + b == a.add(b)

tensor([True, True, True])

In [33]:
a * b == a.mul(b)

tensor([True, True, True])

a.add(b) doesn't change *a*

a.add_(b) changes *b*

In [35]:
a * b
a.mul(b)

tensor([ 7, 10,  9])

In [36]:
a.dot(b)

tensor(26)

In [37]:
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[1,2],[3,4],[5,6]])

In [38]:
a.mm(b)

tensor([[22, 28],
        [49, 64]])

In [39]:
a @ b

tensor([[22, 28],
        [49, 64]])

.mul() and * means elementwise multiplication

.dot() is the dot product

.mm() and @ means matrix multiplication