In [1]:
import numpy as np, torch

In [8]:
torch.manual_seed(42)
np.random.seed(42)

In [9]:
arr = np.random.randint(0,5,6)
arr

array([3, 4, 2, 4, 4, 1])

In [10]:
x = torch.tensor(arr)
x

tensor([3, 4, 2, 4, 4, 1])

In [13]:
x.type(torch.int64)
x.dtype

torch.int64

In [16]:
x = x.reshape(3,2)
x

tensor([[3, 4],
        [2, 4],
        [4, 1]])

In [18]:
x[:,1:]

tensor([[4],
        [4],
        [1]])

In [19]:
x.pow(2)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [21]:
y = torch.randint(0,5,(x.shape[1],4))
y

tensor([[2, 2, 1, 4],
        [1, 0, 0, 4]])

In [22]:
x.mm(y)

tensor([[10,  6,  3, 28],
        [ 8,  4,  2, 24],
        [ 9,  8,  4, 20]])